### ISSUE TITLE
fromWavelet.py

### ISSUE THREAD

**Issue by juanrdzbaeza** [InterComTecMultimedia/intercom#3]
script inverso a toWavelet.py.

debe recibir los planos de información y descifrarlos en un buffer de audio.

**Comment by Rorikid** [comment]
toda la funcionalidad de la transformada y descomposicion y recomposicion de los planos de bits se realiza en fromWavelet.py, por lo que este archivo nunca se creara (razon : su funcionalidad esta recogida en otra libreria)
